#!/usr/bin/env python3
"""Generate Laya's Wasm SIMD i8 dot kernel with a selected K-loop unroll.

Checked-in output makes builds reproducible; --check detects a stale file.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'crates/laya-candle/src/int8_dot_generated.rs'
ROWS = ', '.join(str(i) for i in range(64))
COLS = ', '.join(str(i) for i in range(16))

STEP = '''            {
                let offset = k@@DELTA@@;
                let mut lo = [i32x4_splat(0); C];
                let mut hi = [i32x4_splat(0); C];
                macro_rules! weights {($($c:literal),*)=>{$(if C>$c {
                    let w=unsafe{v128_load(b.as_ptr().add($c*cols+offset).cast())};
                    lo[$c]=i16x8_extend_low_i8x16(w);hi[$c]=i16x8_extend_high_i8x16(w);
                })*};}
                weights!(@@COLS@@);
                macro_rules! columns {($r:literal,$xl:ident,$xh:ident;$($c:literal),*)=>{$(if C>$c {
                    acc[$r][$c]=i32x4_add(acc[$r][$c],i32x4_add(i32x4_dot_i16x8($xl,lo[$c]),i32x4_dot_i16x8($xh,hi[$c])));
                })*};}
                macro_rules! rows {($($r:literal),*)=>{$(if R>$r {
                    let x=unsafe{v128_load(a.as_ptr().add($r*cols+offset).cast())};
                    let xl=i16x8_extend_low_i8x16(x);let xh=i16x8_extend_high_i8x16(x);
                    columns!($r,xl,xh;@@COLS@@);
                })*};}
                rows!(@@ROWS@@);
            }'''

MODULE = '''// Generated by tools/generate_int8_dot.py --unroll @@UNROLL@@. Do not edit.
#[cfg(target_arch = "wasm32")]
#[allow(unsafe_code)]
// K<=16384 bounds every signed i8 dot below 16384*128*128 < i32::MAX.
fn dot_tile<const R: usize, const C: usize>(a: &[i8], b: &[i8], cols: usize) -> [[i32; C]; R] {
    assert!(R <= 64 && C <= 16 && cols <= 16384 && a.len() == R * cols && b.len() == C * cols);
    use std::arch::wasm32::*;
    #[target_feature(enable = "simd128")]
    unsafe fn kernel<const R: usize, const C: usize>(
        a: &[i8], b: &[i8], cols: usize,
    ) -> [[i32; C]; R] {
        let mut acc = [[i32x4_splat(0); C]; R];
        let end = cols / 16 * 16;
        let mut k = 0;
@@LOOP@@
        let mut result = [[0; C]; R];
        macro_rules! store_cols {($r:literal;$($c:literal),*)=>{$(if C>$c {
            let v=acc[$r][$c];result[$r][$c]=i32x4_extract_lane::<0>(v)+i32x4_extract_lane::<1>(v)+i32x4_extract_lane::<2>(v)+i32x4_extract_lane::<3>(v);
        })*};}
        macro_rules! store_rows {($($r:literal),*)=>{$(if R>$r {store_cols!($r;@@COLS@@);})*};}
        store_rows!(@@ROWS@@);
        for i in 0..R {
            for j in 0..C {
                for k in end..cols {
                    result[i][j] += a[i * cols + k] as i32 * b[j * cols + k] as i32;
                }
            }
        }
        result
    }
    // Shapes and accumulator bounds checked above; IC supports simd128.
    unsafe { kernel::<R, C>(a, b, cols) }
}
'''


def step(delta: int) -> str:
    return (STEP.replace('@@DELTA@@', '' if delta == 0 else f' + {delta}')
            .replace('@@COLS@@', COLS).replace('@@ROWS@@', ROWS))


def generate(unroll: int) -> str:
    if unroll not in (1, 2, 3, 4, 6, 8, 16):
        raise ValueError('unroll must be 1, 2, 3, 4, 6, 8, or 16')
    if unroll == 1:
        loop = '        while k < end {\n' + step(0) + '\n            k += 16;\n        }'
    else:
        loop = ('        while k + ' + str(16 * (unroll - 1)) + ' < end {\n'
                + '\n'.join(step(16 * i) for i in range(unroll))
                + '\n            k += ' + str(16 * unroll) + ';\n        }\n'
                + '        while k < end {\n' + step(0) + '\n            k += 16;\n        }')
    return (MODULE.replace('@@UNROLL@@', str(unroll))
            .replace('@@LOOP@@', loop)
            .replace('@@COLS@@', COLS)
            .replace('@@ROWS@@', ROWS))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--unroll', type=int, choices=(1, 2, 3, 4, 6, 8, 16), default=16)
    parser.add_argument('--output', type=Path, default=OUT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate(args.unroll)
    if args.check:
        if not args.output.is_file() or args.output.read_text() != content:
            parser.error(f'{args.output} is stale; run generator with --unroll {args.unroll}')
    else:
        args.output.write_text(content)
        print(args.output)


if __name__ == '__main__':
    main()
